### ISSUE TITLE
Hacktoberfest2019: add interview questions that you have solved

### ISSUE THREAD

**Issue by adityaarakeri** [adityaarakeri/Interview-solved#2]
[HACKTOBERFEST 2019](https://hacktoberfest.digitalocean.com/)
🎉🎉🎉🎉🎉
![hacktoberfest2019](https://raw.githubusercontent.com/adityaarakeri/super-scripts/master/hactoberfest2019.png)

[UPDATED]
Goal:
The entire goal of this issue is to get contributions from the open source community to curate a list of interview questions which are solved in Python(3.7 preferred)

Note:
1. The interview questions can be of any level
2. please do not submit duplicate questions(go through the code base and see if the problem you are submitting exists)
3. All questions should have solutions written in python 3
4. Add tests to test your algorithm inside the root `test` folder
5. view the existing tests for implementation 
6. PR will be rejected if it does not follow the above rules

```
Happy Hacking
```

**Comment by nancydocode** [comment]
yay:tada: I'll add one:octocat:

**Comment by aakankshadhurandhar** [comment]
@adityaarakeri  I want to add question

**Comment by raunaqness** [comment]
@adityaarakeri Hey was lots questions I can add to this. How can I contribute?

**Comment by adityaarakeri** [comment]
follow these steps to contribute
1. make sure your code is in python3(>3.6)
2. add your code file in the appropriate folder, for example: if were solving a leetcode challenge put it in the `leetcode` folder
3. the solution can be a module or a class
4. add tests to test your algorithm in the root `test` folder. 
5. when you create a PR, the CI will run your tests
6. once the tests are passed, we are good to merge it into master

**Comment by raunaqness** [comment]
@adityaarakeri Created a PR!

**Comment by krobitaille93** [comment]
Hi, I am new to open source but I want to contribute a CodeWars problem and solution to the Code Wars folder. I followed a tutorial to use the Command Prompt but then at the end when I type 'git push origin branchname' I get an error saying:

'remote: Permission to adityaarakeri/Interview-solved.git denied to krobitaille93
fatal: unable to access 'https://github.com/adityaarakeri/Interview-solved.git/': The requested URL returned error: 403'

**Comment by stratospher** [comment]
> Hi, I am new to open source but I want to contribute a CodeWars problem and solution to the Code Wars folder. I followed a tutorial to use the Command Prompt but then at the end when I type 'git push origin branchname' I get an error saying:
> 
> 'remote: Permission to adityaarakeri/Interview-solved.git denied to krobitaille93
> fatal: unable to access 'https://github.com/adityaarakeri/Interview-solved.git/': The requested URL returned error: 403'

Try removing your GitHub password from your credential manager and then git push.

**Comment by chttrjeankr** [comment]
> Hi, I am new to open source but I want to contribute a CodeWars problem and solution to the Code Wars folder. I followed a tutorial to use the Command Prompt but then at the end when I type 'git push origin branchname' I get an error saying:
> 
> 'remote: Permission to adityaarakeri/Interview-solved.git denied to krobitaille93
> fatal: unable to access 'https://github.com/adityaarakeri/Interview-solved.git/': The requested URL returned error: 403'

Try "forking" the repository and then "cloning" your version and then "pushing". I guess that'd remove the error.

**Comment by krobitaille93** [comment]
Thanks for the response.

I ended up getting it to work properly by using a different computer. The first computer seemed to have some kind of issue with logging me into GitHub but I was not able to figure out the specific issue.

**Comment by SUBHAMILA** [comment]
Can i contribute to this ? and this is the 1st time iam contributing to open source, so can you guide me with the steps?
Thanks in advance

**Comment by adityaarakeri** [comment]
closing for 2019.
