### ISSUE TITLE
Hacktoberfest2020: add interview questions that you have solved 

### ISSUE THREAD

**Issue by adityaarakeri** [adityaarakeri/Interview-solved#58]
# Hacktoberfest 2020 🎉🎉🎉

Its that time of the year, make PR's in here for your HacktoberFest Contributions

https://hacktoberfest.digitalocean.com/
![Hacktoberfest2020](https://raw.githubusercontent.com/adityaarakeri/super-scripts/master/hacktoberfest2020.png)

### Goal
The entire goal of this issue is to get contributions from the open source community to curate a list of interview questions which are solved in Python(3.7 preferred)

### Note
- The interview questions can be of any level
- Please do not submit duplicate questions(go through the code base and see if the problem you are submitting exists)
- All questions should have solutions written in python 3.8
- Add tests to test your algorithm inside the root test folder
- View the existing tests for implementation
- PR will be rejected if it does not follow the above rules

**Comment by Anmollenka** [comment]
Can I work on this issue?

**Comment by amitkrishna** [comment]
Hi @adityaarakeri  I would like to take this issue had a doubt regarding this . Do we have to submit out own solved code snippets or is there a problem set that has to be solved. I would appreciate if I can get it clarified

**Comment by akshat235** [comment]
Hi please assign this to me. I really want to submit a PR.

**Comment by zmcddn** [comment]
I would like to add a leetcode problem solution, can you assign to me please? I'd like to submit a pr.
Thanks

**Comment by Red-0111** [comment]
hello i want to make a contribution

**Comment by adityaarakeri** [comment]
Create PR's and follow the repo guidelines. please check for duplicate submissions.

**Comment by VishalAmbavade** [comment]
Hi @adityaarakeri, shall I create PR directly? I mean without commenting here before I do it?

**Comment by Anmollenka** [comment]
Hi @adityaarakeri Can you please review my pull request.Thank You.

**Comment by akshat235** [comment]
Hi @adityaarakeri please review my pull requests.

**Comment by dynamoh** [comment]
#95

**Comment by hitblunders** [comment]
@adityaarakeri kindly review my pull request #97
