### ISSUE TITLE
convert all contributions to python 3.8 syntax

### ISSUE THREAD

**Issue by adityaarakeri** [adityaarakeri/Interview-solved#89]
There are few contributions which still include python 2.7 syntax, which needs to be converted to python 3.8 syntax

**Comment by Siddhant-K-code** [comment]
can You pls list it so contributors can easily get it.?

**Comment by adityaarakeri** [comment]
List includes
- print " " should be replaced by print()
- raw_input() should be replace by input()
- more will pop up when you view this repo inside of an ide running python3

**Comment by ImagineZero0** [comment]
Hey..
I just wanted to ask if someone was working on this issue currently.?

**Comment by JaniPaasiluoto** [comment]
I'd like to take this if still available?

**Comment by adityaarakeri** [comment]
@Siddhant-K-code since u asked the question first, are you going to work on it ?

**Comment by ealvarez968** [comment]
Hi,

I would like to contribute to this issue.

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code since u asked the question first, are you going to work on it ?

Yes, I Started working on it. & Will add some more problems of leetcode.

**Comment by Siddhant-K-code** [comment]
@adityaarakeri Please Assign Me!

**Comment by Siddhant-K-code** [comment]
Some programs like `Leetcode/14.py` are giving wrong answers !!

**Comment by Siddhant-K-code** [comment]
@adityaarakeri some files are giving wrong answers and errors , should i change it my Solutions ?

**Comment by adityaarakeri** [comment]
> @adityaarakeri some files are giving wrong answers and errors , can i change it my Solutions ?

Go head.

**Comment by Siddhant-K-code** [comment]
@adityaarakeri Done, Please check My PR #93

**Comment by sowmya8900** [comment]
Hello, How can I contribute to it?
Thanks.

**Comment by vlozan** [comment]
Hi,

Is this section still open for contributions?

Thanks

**Comment by Shreyas-Gupta-21** [comment]
Hello are there any files which still need to be coverted to Python 3 ?
